'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { AdminShell } from '@/components/admin/AdminShell';
import { fetchCategories, fetchProducts } from '@/lib/api-client';

export default function AdminDashboardPage() {
  const [productCount, setProductCount] = useState(0);
  const [categoryCount, setCategoryCount] = useState(0);
  const [isLoading, setIsLoading] = useState(true);
  useEffect(() => { Promise.all([fetchProducts(), fetchCategories()]).then(([products, categories]) => { setProductCount(products.meta.total); setCategoryCount(categories.length); }).finally(() => setIsLoading(false)); }, []);
  return <AdminShell eyebrow="MIG / CONTROL ROOM" title="نمای کلی عملیات"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div className="border border-neutral-200 bg-white p-6 dark:border-white/10 dark:bg-[#1b1d1b]"><span className="eyebrow">PRODUCTS</span><strong className="mt-5 block text-4xl font-black text-primary-500">{isLoading ? '—' : productCount}</strong><span className="mt-2 block text-sm text-neutral-500">محصول فعال در کاتالوگ</span></div><div className="border border-neutral-200 bg-white p-6 dark:border-white/10 dark:bg-[#1b1d1b]"><span className="eyebrow">CATEGORIES</span><strong className="mt-5 block text-4xl font-black text-primary-500">{isLoading ? '—' : categoryCount}</strong><span className="mt-2 block text-sm text-neutral-500">دسته‌بندی محصول</span></div><div className="border border-neutral-200 bg-white p-6 dark:border-white/10 dark:bg-[#1b1d1b]"><span className="eyebrow">CUSTOMERS</span><strong className="mt-5 block text-4xl font-black text-primary-500">—</strong><span className="mt-2 block text-sm text-neutral-500">در مرحله بعدی</span></div><div className="border border-neutral-200 bg-white p-6 dark:border-white/10 dark:bg-[#1b1d1b]"><span className="eyebrow">SYSTEM</span><strong className="mt-5 block text-4xl font-black text-green-600">OK</strong><span className="mt-2 block text-sm text-neutral-500">API و دیتابیس فعال</span></div></div><section className="mt-10 grid gap-5 lg:grid-cols-2"><Link href="/admin/products" className="group border border-neutral-200 bg-neutral-900 p-7 text-white transition hover:border-primary-500 dark:border-white/10"><span className="eyebrow">01 / CATALOG</span><h2 className="mt-12 text-3xl font-black">مدیریت محصولات</h2><p className="mt-3 text-sm leading-7 text-neutral-400">ایجاد، بررسی و حذف محصولات کاتالوگ MIG.</p><span className="mt-8 inline-block text-primary-500 transition group-hover:translate-x-1">ورود به مدیریت ←</span></Link><Link href="/account" className="group border border-neutral-200 bg-white p-7 transition hover:border-primary-500 dark:border-white/10 dark:bg-[#1b1d1b]"><span className="eyebrow">02 / CUSTOMER FLOW</span><h2 className="mt-12 text-3xl font-black">مرکز مشتریان</h2><p className="mt-3 text-sm leading-7 text-neutral-500">پیش‌فاکتورها، سفارش‌ها و پرداخت‌های مشتریان.</p><span className="mt-8 inline-block text-primary-600 transition group-hover:translate-x-1 dark:text-primary-500">مشاهده جریان مشتری ←</span></Link></section></AdminShell>;
}
